<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet Package Info -->
    <PackageId>TaskRunnerSharp</PackageId>
    <Version>1.0.3</Version>
    <Authors>Nagib Sabbag Filho</Authors>
    <Company>Nagib Sabbag Filho</Company>
    <Product>TaskRunnerSharp</Product>
    <Description>Simple, lightweight, and thread-safe task orchestration for .NET applications. Manage, run, and monitor multiple tasks with ease.</Description>
    <PackageTags>task async await runner utilities concurrency parallel</PackageTags>
    <RepositoryUrl>https://github.com/na-sabbag/task-runner-sharp</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/na-sabbag/task-runner-sharp</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>

    <!-- NuGet Settings -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <!-- Include README in the NuGet package -->
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>